#!/bin/bash

image=hub.juniper.net/contrail/contrail-command-deployer:__container_tag__

install()
{
    yum install -y yum-utils device-mapper-persistent-data lvm2
    yum-config-manager \
      --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    yum install -y docker-ce
    systemctl start docker
#    cat << __EOT__ > /etc/docker/daemon.json
#{
#    "insecure-registries": [
#        "ci-repo.englab.juniper.net:5010"
#    ]
#}
#__EOT__
#    systemctl restart docker

}

launch_with_new_cluster()
{
    docker run -t --net host -d --privileged \
      -v /root/command_servers.yml:/command_servers.yml \
      --name contrail_command_deployer \
      $image
}


launch()
{
    docker login hub.juniper.net \
      --username __registry_username__ \
      --password __registry_password__
    docker pull $image

    docker run -t --net host -d --privileged \
      -e orchestrator=openstack \
      -e action=import_cluster \
      -v /root/instances.yaml:/instances.yml \
      -v /root/command_servers.yml:/command_servers.yml \
      --name contrail_command_deployer \
      $image
}

delete()
{
    docker stop contrail_command
    docker stop contrail_mysql
    docker rm contrail_command
    docker rm contrail_mysql
    docker rm contrail_command_deployer
    rm -fr /var/lib/docker/volumes/*
}

main()
{
    case "$1" in
        install)
            install
            ;;
        launch)
            launch
            ;;
        delete)
            delete
            ;;
        *)
            echo "Help"
            ;;
    esac
}

main "$@"
exit 0

